//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<BACKSALE> BACKSALEs { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILL_ACADEMIC> BILL_ACADEMIC { get; set; }
        public virtual DbSet<BILL_DATA> BILL_DATA { get; set; }
        public virtual DbSet<BILL_DATA_COUNT> BILL_DATA_COUNT { get; set; }
        public virtual DbSet<BILL_DATA_DETAIL> BILL_DATA_DETAIL { get; set; }
        public virtual DbSet<BILL_DIED> BILL_DIED { get; set; }
        public virtual DbSet<BILL_EMERGENCYMEDICAL> BILL_EMERGENCYMEDICAL { get; set; }
        public virtual DbSet<BILL_EMERGENCYOTHER> BILL_EMERGENCYOTHER { get; set; }
        public virtual DbSet<BILL_HACCOMPANY> BILL_HACCOMPANY { get; set; }
        public virtual DbSet<BILL_HBACK> BILL_HBACK { get; set; }
        public virtual DbSet<BILL_HBURIAL> BILL_HBURIAL { get; set; }
        public virtual DbSet<BILL_HCHANGE> BILL_HCHANGE { get; set; }
        public virtual DbSet<BILL_HMEDIA> BILL_HMEDIA { get; set; }
        public virtual DbSet<BILL_HVISIT> BILL_HVISIT { get; set; }
        public virtual DbSet<BILL_INJURE> BILL_INJURE { get; set; }
        public virtual DbSet<BILL_LOSE> BILL_LOSE { get; set; }
        public virtual DbSet<BILL_OTHER> BILL_OTHER { get; set; }
        public virtual DbSet<BILL_TRAVELDELAY> BILL_TRAVELDELAY { get; set; }
        public virtual DbSet<BROKERAGE> BROKERAGEs { get; set; }
        public virtual DbSet<COMPANYBROKERAGE> COMPANYBROKERAGEs { get; set; }
        public virtual DbSet<COMPANYMONEY> COMPANYMONEYs { get; set; }
        public virtual DbSet<CUSTOM> CUSTOMs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<DUTYITEM> DUTYITEMs { get; set; }
        public virtual DbSet<FAVOREE> FAVOREEs { get; set; }
        public virtual DbSet<HOSPITAL> HOSPITALs { get; set; }
        public virtual DbSet<INTEREST_ORDER> INTEREST_ORDER { get; set; }
        public virtual DbSet<INTEREST_ORDEROTHER> INTEREST_ORDEROTHER { get; set; }
        public virtual DbSet<INTEREST_PRODUCE> INTEREST_PRODUCE { get; set; }
        public virtual DbSet<INTEREST_PRODUCEOTHER> INTEREST_PRODUCEOTHER { get; set; }
        public virtual DbSet<IO_DUTY> IO_DUTY { get; set; }
        public virtual DbSet<IO_ITEM> IO_ITEM { get; set; }
        public virtual DbSet<IO_OTHER_ITEM> IO_OTHER_ITEM { get; set; }
        public virtual DbSet<IP_DUTY> IP_DUTY { get; set; }
        public virtual DbSet<IP_ITEM> IP_ITEM { get; set; }
        public virtual DbSet<IPOTHER_ITEM> IPOTHER_ITEM { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONs { get; set; }
        public virtual DbSet<PHARMACY> PHARMACies { get; set; }
        public virtual DbSet<PRODUCE> PRODUCEs { get; set; }
        public virtual DbSet<QUESTION> QUESTIONs { get; set; }
        public virtual DbSet<RECOMMENDHOSPITAL> RECOMMENDHOSPITALs { get; set; }
        public virtual DbSet<RECORD> RECORDs { get; set; }
        public virtual DbSet<RELATIONPEOPLE> RELATIONPEOPLEs { get; set; }
        public virtual DbSet<REPORTINFORMATION> REPORTINFORMATIONs { get; set; }
        public virtual DbSet<RESULT> RESULTs { get; set; }
        public virtual DbSet<RESULT_DUTY> RESULT_DUTY { get; set; }
        public virtual DbSet<RESULT_ITEM> RESULT_ITEM { get; set; }
        public virtual DbSet<RESULT_OTHER> RESULT_OTHER { get; set; }
        public virtual DbSet<RI_ACADEMIC> RI_ACADEMIC { get; set; }
        public virtual DbSet<RI_DIED> RI_DIED { get; set; }
        public virtual DbSet<RI_HACCOMPANY> RI_HACCOMPANY { get; set; }
        public virtual DbSet<RI_HBACK> RI_HBACK { get; set; }
        public virtual DbSet<RI_HBURIAL> RI_HBURIAL { get; set; }
        public virtual DbSet<RI_HCHANGE> RI_HCHANGE { get; set; }
        public virtual DbSet<RI_HMEDIA> RI_HMEDIA { get; set; }
        public virtual DbSet<RI_HVISIT> RI_HVISIT { get; set; }
        public virtual DbSet<RI_INJURE> RI_INJURE { get; set; }
        public virtual DbSet<RI_LOSE> RI_LOSE { get; set; }
        public virtual DbSet<RI_MEDICAL> RI_MEDICAL { get; set; }
        public virtual DbSet<RI_OTHER> RI_OTHER { get; set; }
        public virtual DbSet<RI_TRAVELDELAY> RI_TRAVELDELAY { get; set; }
        public virtual DbSet<SALESDETAIL> SALESDETAILs { get; set; }
        public virtual DbSet<SAMU> SAMUs { get; set; }
        public virtual DbSet<SCHOOL> SCHOOLs { get; set; }
        public virtual DbSet<SCHOOL_MEDICALRESOURCE> SCHOOL_MEDICALRESOURCE { get; set; }
    }
}
